import './globals.css';

import { AuthContextProvider } from '@/context/AuthContext';
import Navbar from '../../components/Navbar';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <head></head>
            <body>
                <AuthContextProvider>
                    <header>
                        <Navbar />
                    </header>

                    {children}
                </AuthContextProvider>
            </body>
        </html>
    );
}
